services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./alembic.ini:/app/alembic.ini  # Монтируем alembic.ini
      - ./alembic:/app/alembic  # Монтируем директорию alembic
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/users_db
      - ALEMBIC_DATABASE_URL=postgresql+psycopg2://user:password@db:5432/users_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d users_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
