apiVersion: v1
kind: ConfigMap
metadata:
  name: user-api-config
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: users_db
  DB_USER: user
  DB_PASSWORD: password
  RMQ_URL: amqp://guest:guest@rabbitmq/
  APP_PORT: "8000"
