apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: user-api:latest
          command: ["python", "-m", "src.app.worker.worker"]
          envFrom:
            - configMapRef:
                name: user-api-config
